"""
Curated skill database — maps skill names/aliases to categories.
Used for skill extraction and normalisation.
"""
from __future__ import annotations

from typing import Dict, Any

# Format: { "alias_or_canonical": {"category": "...", "canonical": "...", "confidence": 0.9} }
SKILL_DB: Dict[str, Dict[str, Any]] = {
    # ── Programming Languages ──────────────────────────────────────────────
    "python": {"category": "Programming Languages", "canonical": "Python", "confidence": 1.0},
    "javascript": {"category": "Programming Languages", "canonical": "JavaScript", "confidence": 1.0},
    "js": {"category": "Programming Languages", "canonical": "JavaScript", "confidence": 0.9},
    "typescript": {"category": "Programming Languages", "canonical": "TypeScript", "confidence": 1.0},
    "ts": {"category": "Programming Languages", "canonical": "TypeScript", "confidence": 0.85},
    "java": {"category": "Programming Languages", "canonical": "Java", "confidence": 1.0},
    "c++": {"category": "Programming Languages", "canonical": "C++", "confidence": 1.0},
    "c#": {"category": "Programming Languages", "canonical": "C#", "confidence": 1.0},
    "c": {"category": "Programming Languages", "canonical": "C", "confidence": 0.7},
    "rust": {"category": "Programming Languages", "canonical": "Rust", "confidence": 1.0},
    "go": {"category": "Programming Languages", "canonical": "Go", "confidence": 0.9},
    "golang": {"category": "Programming Languages", "canonical": "Go", "confidence": 1.0},
    "kotlin": {"category": "Programming Languages", "canonical": "Kotlin", "confidence": 1.0},
    "swift": {"category": "Programming Languages", "canonical": "Swift", "confidence": 1.0},
    "ruby": {"category": "Programming Languages", "canonical": "Ruby", "confidence": 1.0},
    "php": {"category": "Programming Languages", "canonical": "PHP", "confidence": 1.0},
    "scala": {"category": "Programming Languages", "canonical": "Scala", "confidence": 1.0},
    "r": {"category": "Programming Languages", "canonical": "R", "confidence": 0.6},
    "matlab": {"category": "Programming Languages", "canonical": "MATLAB", "confidence": 1.0},
    "perl": {"category": "Programming Languages", "canonical": "Perl", "confidence": 1.0},
    "shell": {"category": "Programming Languages", "canonical": "Shell/Bash", "confidence": 0.9},
    "bash": {"category": "Programming Languages", "canonical": "Shell/Bash", "confidence": 1.0},
    "powershell": {"category": "Programming Languages", "canonical": "PowerShell", "confidence": 1.0},
    "html": {"category": "Programming Languages", "canonical": "HTML", "confidence": 1.0},
    "html5": {"category": "Programming Languages", "canonical": "HTML", "confidence": 1.0},
    "css": {"category": "Programming Languages", "canonical": "CSS", "confidence": 1.0},
    "css3": {"category": "Programming Languages", "canonical": "CSS", "confidence": 1.0},

    # ── Frameworks & Libraries ──────────────────────────────────────────────
    "react": {"category": "Frameworks & Libraries", "canonical": "React", "confidence": 1.0},
    "react.js": {"category": "Frameworks & Libraries", "canonical": "React", "confidence": 1.0},
    "reactjs": {"category": "Frameworks & Libraries", "canonical": "React", "confidence": 1.0},
    "angular": {"category": "Frameworks & Libraries", "canonical": "Angular", "confidence": 1.0},
    "vue": {"category": "Frameworks & Libraries", "canonical": "Vue.js", "confidence": 1.0},
    "vue.js": {"category": "Frameworks & Libraries", "canonical": "Vue.js", "confidence": 1.0},
    "vuejs": {"category": "Frameworks & Libraries", "canonical": "Vue.js", "confidence": 1.0},
    "next.js": {"category": "Frameworks & Libraries", "canonical": "Next.js", "confidence": 1.0},
    "nextjs": {"category": "Frameworks & Libraries", "canonical": "Next.js", "confidence": 1.0},
    "nuxt": {"category": "Frameworks & Libraries", "canonical": "Nuxt.js", "confidence": 1.0},
    "svelte": {"category": "Frameworks & Libraries", "canonical": "Svelte", "confidence": 1.0},
    "django": {"category": "Frameworks & Libraries", "canonical": "Django", "confidence": 1.0},
    "flask": {"category": "Frameworks & Libraries", "canonical": "Flask", "confidence": 1.0},
    "fastapi": {"category": "Frameworks & Libraries", "canonical": "FastAPI", "confidence": 1.0},
    "spring": {"category": "Frameworks & Libraries", "canonical": "Spring", "confidence": 1.0},
    "spring boot": {"category": "Frameworks & Libraries", "canonical": "Spring Boot", "confidence": 1.0},
    "express": {"category": "Frameworks & Libraries", "canonical": "Express.js", "confidence": 1.0},
    "express.js": {"category": "Frameworks & Libraries", "canonical": "Express.js", "confidence": 1.0},
    "node.js": {"category": "Frameworks & Libraries", "canonical": "Node.js", "confidence": 1.0},
    "nodejs": {"category": "Frameworks & Libraries", "canonical": "Node.js", "confidence": 1.0},
    "nest.js": {"category": "Frameworks & Libraries", "canonical": "NestJS", "confidence": 1.0},
    "nestjs": {"category": "Frameworks & Libraries", "canonical": "NestJS", "confidence": 1.0},
    "laravel": {"category": "Frameworks & Libraries", "canonical": "Laravel", "confidence": 1.0},
    "rails": {"category": "Frameworks & Libraries", "canonical": "Ruby on Rails", "confidence": 1.0},
    "ruby on rails": {"category": "Frameworks & Libraries", "canonical": "Ruby on Rails", "confidence": 1.0},
    "tensorflow": {"category": "Frameworks & Libraries", "canonical": "TensorFlow", "confidence": 1.0},
    "pytorch": {"category": "Frameworks & Libraries", "canonical": "PyTorch", "confidence": 1.0},
    "keras": {"category": "Frameworks & Libraries", "canonical": "Keras", "confidence": 1.0},
    "scikit-learn": {"category": "Frameworks & Libraries", "canonical": "Scikit-learn", "confidence": 1.0},
    "sklearn": {"category": "Frameworks & Libraries", "canonical": "Scikit-learn", "confidence": 1.0},
    "pandas": {"category": "Frameworks & Libraries", "canonical": "Pandas", "confidence": 1.0},
    "numpy": {"category": "Frameworks & Libraries", "canonical": "NumPy", "confidence": 1.0},
    "langchain": {"category": "Frameworks & Libraries", "canonical": "LangChain", "confidence": 1.0},
    "hugging face": {"category": "Frameworks & Libraries", "canonical": "Hugging Face", "confidence": 1.0},
    "huggingface": {"category": "Frameworks & Libraries", "canonical": "Hugging Face", "confidence": 1.0},
    "apache spark": {"category": "Frameworks & Libraries", "canonical": "Apache Spark", "confidence": 1.0},
    "spark": {"category": "Frameworks & Libraries", "canonical": "Apache Spark", "confidence": 0.9},
    "airflow": {"category": "Frameworks & Libraries", "canonical": "Airflow", "confidence": 0.95},
    "dbt": {"category": "Frameworks & Libraries", "canonical": "dbt", "confidence": 0.9},
    "mlflow": {"category": "Frameworks & Libraries", "canonical": "MLflow", "confidence": 0.9},
    "prisma": {"category": "Frameworks & Libraries", "canonical": "Prisma", "confidence": 0.9},
    "jest": {"category": "Frameworks & Libraries", "canonical": "Jest", "confidence": 1.0},
    "selenium": {"category": "Frameworks & Libraries", "canonical": "Selenium", "confidence": 1.0},
    "cypress": {"category": "Frameworks & Libraries", "canonical": "Cypress", "confidence": 1.0},
    "playwright": {"category": "Frameworks & Libraries", "canonical": "Playwright", "confidence": 1.0},
    "react native": {"category": "Frameworks & Libraries", "canonical": "React Native", "confidence": 1.0},
    "react-native": {"category": "Frameworks & Libraries", "canonical": "React Native", "confidence": 1.0},
    "flutter": {"category": "Frameworks & Libraries", "canonical": "Flutter", "confidence": 1.0},
    "tailwind css": {"category": "Frameworks & Libraries", "canonical": "Tailwind CSS", "confidence": 1.0},
    "tailwindcss": {"category": "Frameworks & Libraries", "canonical": "Tailwind CSS", "confidence": 1.0},
    "tailwind": {"category": "Frameworks & Libraries", "canonical": "Tailwind CSS", "confidence": 0.9},

    # ── Databases ──────────────────────────────────────────────────────────
    "postgresql": {"category": "Databases", "canonical": "PostgreSQL", "confidence": 1.0},
    "postgres": {"category": "Databases", "canonical": "PostgreSQL", "confidence": 1.0},
    "mysql": {"category": "Databases", "canonical": "MySQL", "confidence": 1.0},
    "sqlite": {"category": "Databases", "canonical": "SQLite", "confidence": 1.0},
    "mongodb": {"category": "Databases", "canonical": "MongoDB", "confidence": 1.0},
    "mongo": {"category": "Databases", "canonical": "MongoDB", "confidence": 0.9},
    "redis": {"category": "Databases", "canonical": "Redis", "confidence": 1.0},
    "elasticsearch": {"category": "Databases", "canonical": "Elasticsearch", "confidence": 1.0},
    "oracle": {"category": "Databases", "canonical": "Oracle DB", "confidence": 0.85},
    "cassandra": {"category": "Databases", "canonical": "Cassandra", "confidence": 1.0},
    "dynamodb": {"category": "Databases", "canonical": "DynamoDB", "confidence": 1.0},
    "firestore": {"category": "Databases", "canonical": "Firestore", "confidence": 1.0},
    "neo4j": {"category": "Databases", "canonical": "Neo4j", "confidence": 1.0},
    "mssql": {"category": "Databases", "canonical": "SQL Server", "confidence": 1.0},
    "sql server": {"category": "Databases", "canonical": "SQL Server", "confidence": 1.0},
    "mariadb": {"category": "Databases", "canonical": "MariaDB", "confidence": 1.0},
    "sql": {"category": "Databases", "canonical": "SQL", "confidence": 1.0},
    "snowflake": {"category": "Databases", "canonical": "Snowflake", "confidence": 0.95},
    "redshift": {"category": "Databases", "canonical": "Redshift", "confidence": 0.95},
    "databricks": {"category": "Databases", "canonical": "Databricks", "confidence": 0.95},

    # ── Cloud & DevOps ──────────────────────────────────────────────────────
    "aws": {"category": "Cloud & DevOps", "canonical": "AWS", "confidence": 1.0},
    "amazon web services": {"category": "Cloud & DevOps", "canonical": "AWS", "confidence": 1.0},
    "azure": {"category": "Cloud & DevOps", "canonical": "Azure", "confidence": 1.0},
    "gcp": {"category": "Cloud & DevOps", "canonical": "GCP", "confidence": 1.0},
    "google cloud": {"category": "Cloud & DevOps", "canonical": "GCP", "confidence": 1.0},
    "docker": {"category": "Cloud & DevOps", "canonical": "Docker", "confidence": 1.0},
    "kubernetes": {"category": "Cloud & DevOps", "canonical": "Kubernetes", "confidence": 1.0},
    "k8s": {"category": "Cloud & DevOps", "canonical": "Kubernetes", "confidence": 1.0},
    "terraform": {"category": "Cloud & DevOps", "canonical": "Terraform", "confidence": 1.0},
    "ansible": {"category": "Cloud & DevOps", "canonical": "Ansible", "confidence": 1.0},
    "jenkins": {"category": "Cloud & DevOps", "canonical": "Jenkins", "confidence": 1.0},
    "github actions": {"category": "Cloud & DevOps", "canonical": "GitHub Actions", "confidence": 1.0},
    "gitlab ci": {"category": "Cloud & DevOps", "canonical": "GitLab CI/CD", "confidence": 1.0},
    "ci/cd": {"category": "Cloud & DevOps", "canonical": "CI/CD", "confidence": 1.0},
    "helm": {"category": "Cloud & DevOps", "canonical": "Helm", "confidence": 1.0},
    "prometheus": {"category": "Cloud & DevOps", "canonical": "Prometheus", "confidence": 1.0},
    "grafana": {"category": "Cloud & DevOps", "canonical": "Grafana", "confidence": 1.0},
    "linux": {"category": "Cloud & DevOps", "canonical": "Linux", "confidence": 1.0},
    "nginx": {"category": "Cloud & DevOps", "canonical": "Nginx", "confidence": 1.0},
    "apache": {"category": "Cloud & DevOps", "canonical": "Apache", "confidence": 0.85},
    "monitoring": {"category": "Cloud & DevOps", "canonical": "Monitoring", "confidence": 0.8},

    # ── Tools & Platforms ──────────────────────────────────────────────────
    "git": {"category": "Tools & Platforms", "canonical": "Git", "confidence": 1.0},
    "github": {"category": "Tools & Platforms", "canonical": "GitHub", "confidence": 1.0},
    "gitlab": {"category": "Tools & Platforms", "canonical": "GitLab", "confidence": 1.0},
    "bitbucket": {"category": "Tools & Platforms", "canonical": "Bitbucket", "confidence": 1.0},
    "jira": {"category": "Tools & Platforms", "canonical": "Jira", "confidence": 1.0},
    "confluence": {"category": "Tools & Platforms", "canonical": "Confluence", "confidence": 1.0},
    "figma": {"category": "Tools & Platforms", "canonical": "Figma", "confidence": 1.0},
    "vscode": {"category": "Tools & Platforms", "canonical": "VS Code", "confidence": 1.0},
    "visual studio code": {"category": "Tools & Platforms", "canonical": "VS Code", "confidence": 1.0},
    "postman": {"category": "Tools & Platforms", "canonical": "Postman", "confidence": 1.0},
    "graphql": {"category": "Tools & Platforms", "canonical": "GraphQL", "confidence": 1.0},
    "rest api": {"category": "Tools & Platforms", "canonical": "REST API", "confidence": 1.0},
    "rest apis": {"category": "Tools & Platforms", "canonical": "REST API", "confidence": 1.0},
    "restful api": {"category": "Tools & Platforms", "canonical": "REST API", "confidence": 1.0},
    "restful apis": {"category": "Tools & Platforms", "canonical": "REST API", "confidence": 1.0},
    "restful": {"category": "Tools & Platforms", "canonical": "REST API", "confidence": 0.9},
    "grpc": {"category": "Tools & Platforms", "canonical": "gRPC", "confidence": 1.0},
    "kafka": {"category": "Tools & Platforms", "canonical": "Apache Kafka", "confidence": 1.0},
    "rabbitmq": {"category": "Tools & Platforms", "canonical": "RabbitMQ", "confidence": 1.0},
    "celery": {"category": "Tools & Platforms", "canonical": "Celery", "confidence": 1.0},
    "excel": {"category": "Tools & Platforms", "canonical": "Excel", "confidence": 0.9},
    "power bi": {"category": "Tools & Platforms", "canonical": "Power BI", "confidence": 1.0},
    "powerbi": {"category": "Tools & Platforms", "canonical": "Power BI", "confidence": 1.0},
    "tableau": {"category": "Tools & Platforms", "canonical": "Tableau", "confidence": 1.0},
    "looker": {"category": "Tools & Platforms", "canonical": "Looker", "confidence": 0.95},
    "firebase": {"category": "Tools & Platforms", "canonical": "Firebase", "confidence": 1.0},

    # ── Soft Skills ────────────────────────────────────────────────────────
    "leadership": {"category": "Soft Skills", "canonical": "Leadership", "confidence": 0.8},
    "communication": {"category": "Soft Skills", "canonical": "Communication", "confidence": 0.8},
    "teamwork": {"category": "Soft Skills", "canonical": "Teamwork", "confidence": 0.8},
    "problem solving": {"category": "Soft Skills", "canonical": "Problem Solving", "confidence": 0.8},
    "agile": {"category": "Soft Skills", "canonical": "Agile", "confidence": 0.85},
    "scrum": {"category": "Soft Skills", "canonical": "Scrum", "confidence": 0.85},
    "kanban": {"category": "Soft Skills", "canonical": "Kanban", "confidence": 0.85},
    "project management": {"category": "Soft Skills", "canonical": "Project Management", "confidence": 0.85},
    "mentoring": {"category": "Soft Skills", "canonical": "Mentoring", "confidence": 0.8},
    "code review": {"category": "Soft Skills", "canonical": "Code Review", "confidence": 0.85},

    # ── Domain Knowledge ───────────────────────────────────────────────────
    "machine learning": {"category": "Domain Knowledge", "canonical": "Machine Learning", "confidence": 1.0},
    "deep learning": {"category": "Domain Knowledge", "canonical": "Deep Learning", "confidence": 1.0},
    "nlp": {"category": "Domain Knowledge", "canonical": "NLP", "confidence": 1.0},
    "natural language processing": {"category": "Domain Knowledge", "canonical": "NLP", "confidence": 1.0},
    "computer vision": {"category": "Domain Knowledge", "canonical": "Computer Vision", "confidence": 1.0},
    "data science": {"category": "Domain Knowledge", "canonical": "Data Science", "confidence": 1.0},
    "data engineering": {"category": "Domain Knowledge", "canonical": "Data Engineering", "confidence": 1.0},
    "devops": {"category": "Domain Knowledge", "canonical": "DevOps", "confidence": 1.0},
    "mlops": {"category": "Domain Knowledge", "canonical": "MLOps", "confidence": 1.0},
    "system design": {"category": "Domain Knowledge", "canonical": "System Design", "confidence": 0.9},
    "microservices": {"category": "Domain Knowledge", "canonical": "Microservices", "confidence": 1.0},
    "distributed systems": {"category": "Domain Knowledge", "canonical": "Distributed Systems", "confidence": 1.0},
    "cybersecurity": {"category": "Domain Knowledge", "canonical": "Cybersecurity", "confidence": 1.0},
    "blockchain": {"category": "Domain Knowledge", "canonical": "Blockchain", "confidence": 1.0},
    "web3": {"category": "Domain Knowledge", "canonical": "Web3", "confidence": 1.0},
    "etl": {"category": "Domain Knowledge", "canonical": "ETL", "confidence": 1.0},
    "data analysis": {"category": "Domain Knowledge", "canonical": "Data Analysis", "confidence": 0.9},
    "data analytics": {"category": "Domain Knowledge", "canonical": "Data Analysis", "confidence": 0.9},
    "data visualisation": {"category": "Domain Knowledge", "canonical": "Data Visualisation", "confidence": 0.9},
    "data visualization": {"category": "Domain Knowledge", "canonical": "Data Visualisation", "confidence": 0.9},
    "statistics": {"category": "Domain Knowledge", "canonical": "Statistics", "confidence": 0.9},
    "a/b testing": {"category": "Domain Knowledge", "canonical": "A/B Testing", "confidence": 0.9},
    "data warehousing": {"category": "Domain Knowledge", "canonical": "Data Warehousing", "confidence": 0.9},
    "user research": {"category": "Domain Knowledge", "canonical": "User Research", "confidence": 0.9},
    "wireframing": {"category": "Domain Knowledge", "canonical": "Wireframing", "confidence": 0.9},
    "prototyping": {"category": "Domain Knowledge", "canonical": "Prototyping", "confidence": 0.9},
    "usability testing": {"category": "Domain Knowledge", "canonical": "Usability Testing", "confidence": 0.9},
    "interaction design": {"category": "Domain Knowledge", "canonical": "Interaction Design", "confidence": 0.9},
    "design systems": {"category": "Domain Knowledge", "canonical": "Design Systems", "confidence": 0.9},
    "accessibility": {"category": "Domain Knowledge", "canonical": "Accessibility", "confidence": 0.8},
    "product strategy": {"category": "Domain Knowledge", "canonical": "Product Strategy", "confidence": 0.85},
    "roadmap planning": {"category": "Domain Knowledge", "canonical": "Roadmap Planning", "confidence": 0.85},
    "requirements gathering": {"category": "Domain Knowledge", "canonical": "Requirements Gathering", "confidence": 0.85},
    "process mapping": {"category": "Domain Knowledge", "canonical": "Process Mapping", "confidence": 0.85},
    "stakeholder management": {"category": "Domain Knowledge", "canonical": "Stakeholder Management", "confidence": 0.85},
    "networking": {"category": "Domain Knowledge", "canonical": "Networking", "confidence": 0.8},
    "application security": {"category": "Domain Knowledge", "canonical": "Application Security", "confidence": 1.0},
    "penetration testing": {"category": "Domain Knowledge", "canonical": "Penetration Testing", "confidence": 1.0},
    "incident response": {"category": "Domain Knowledge", "canonical": "Incident Response", "confidence": 0.95},
    "threat modelling": {"category": "Domain Knowledge", "canonical": "Threat Modelling", "confidence": 0.9},
    "threat modeling": {"category": "Domain Knowledge", "canonical": "Threat Modelling", "confidence": 0.9},
    "cloud security": {"category": "Domain Knowledge", "canonical": "Cloud Security", "confidence": 0.9},
}


def normalise_skill(name: str) -> str:
    """Return the canonical name for a skill."""
    entry = SKILL_DB.get(name.lower())
    if entry:
        return entry.get("canonical", name)
    return name.strip().title()
